const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "mongodb+srv://theobot:theobot@cluster0.nj0fs2q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "postgres://u86b91ha7kn7sq:pf9929dc53188366098cd46987ab9938ebcbfbce32a85cf445a447ebcabf2f57b@c5flugvup2318r.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/deoounlpb9jadg"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Africa/Lagos";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.postimg.cc/Jz0Lnts6/theohacker2.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ 𝕆𝕝𝕒😈🦍 MD" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 4
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "recording" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_14_23_10_14_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMTk1LFxuICAgICAgICAxOSxcbiAgICAgICAgMTg0LFxuICAgICAgICA5MCxcbiAgICAgICAgMTkxLFxuICAgICAgICA1OSxcbiAgICAgICAgMTUwLFxuICAgICAgICAxNjgsXG4gICAgICAgIDUyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTk3LFxuICAgICAgICAxMTEsXG4gICAgICAgIDEzLFxuICAgICAgICAxMTUsXG4gICAgICAgIDE5OSxcbiAgICAgICAgNTMsXG4gICAgICAgIDY1LFxuICAgICAgICAxMjksXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTIxLFxuICAgICAgICAxMjYsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjU1LFxuICAgICAgICAxNyxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE5MixcbiAgICAgICAgODEsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTA5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTc4LFxuICAgICAgICA1MCxcbiAgICAgICAgOTIsXG4gICAgICAgIDU2LFxuICAgICAgICA2MCxcbiAgICAgICAgOTEsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTg4LFxuICAgICAgICA2MixcbiAgICAgICAgMzksXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjA1LFxuICAgICAgICAxMTcsXG4gICAgICAgIDgzLFxuICAgICAgICA3MSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNzQsXG4gICAgICAgIDMzLFxuICAgICAgICAyMzcsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjUzLFxuICAgICAgICAxMDEsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNDQsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTY4LFxuICAgICAgICAxMzEsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTMxLFxuICAgICAgICAxNTQsXG4gICAgICAgIDEzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1NixcbiAgICAgICAgMjA1LFxuICAgICAgICA0OSxcbiAgICAgICAgMjM5LFxuICAgICAgICAzMyxcbiAgICAgICAgNTMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTU0LFxuICAgICAgICAxOTcsXG4gICAgICAgIDQxLFxuICAgICAgICAxMDcsXG4gICAgICAgIDY2LFxuICAgICAgICAxMjAsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNDEsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjU0LFxuICAgICAgICA3NCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAyNDgsXG4gICAgICAgIDg4LFxuICAgICAgICA1NSxcbiAgICAgICAgNDQsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTU2LFxuICAgICAgICAyMjYsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTAyLFxuICAgICAgICA4OCxcbiAgICAgICAgOTcsXG4gICAgICAgIDExMCxcbiAgICAgICAgODNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE1LFxuICAgICAgICAzOSxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMzQsXG4gICAgICAgIDU2LFxuICAgICAgICAxMzQsXG4gICAgICAgIDQzLFxuICAgICAgICA5NixcbiAgICAgICAgMjIwLFxuICAgICAgICAyMTQsXG4gICAgICAgIDE4MixcbiAgICAgICAgODEsXG4gICAgICAgIDQyLFxuICAgICAgICAzMCxcbiAgICAgICAgMTEsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjE4LFxuICAgICAgICA1LFxuICAgICAgICAxMDUsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTcxLFxuICAgICAgICAyNixcbiAgICAgICAgNjcsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTc3LFxuICAgICAgICAyNTQsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTAsXG4gICAgICAgIDYsXG4gICAgICAgIDIsXG4gICAgICAgIDk4LFxuICAgICAgICAzNlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICA1OCxcbiAgICAgICAgMjE5LFxuICAgICAgICAxNDcsXG4gICAgICAgIDI0LFxuICAgICAgICA3MSxcbiAgICAgICAgNzAsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTUwLFxuICAgICAgICA4OCxcbiAgICAgICAgOTIsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTQ5LFxuICAgICAgICAxMDUsXG4gICAgICAgIDIzNixcbiAgICAgICAgOTIsXG4gICAgICAgIDk0LFxuICAgICAgICAxNjIsXG4gICAgICAgIDI0MixcbiAgICAgICAgOSxcbiAgICAgICAgODksXG4gICAgICAgIDI0NixcbiAgICAgICAgMjUzLFxuICAgICAgICAxOTcsXG4gICAgICAgIDU1LFxuICAgICAgICA1NSxcbiAgICAgICAgMTMxLFxuICAgICAgICAxMTMsXG4gICAgICAgIDM3LFxuICAgICAgICAyMTQsXG4gICAgICAgIDQyLFxuICAgICAgICAxMDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjksXG4gICAgICAgIDQ1LFxuICAgICAgICAyMDUsXG4gICAgICAgIDg5LFxuICAgICAgICAxMzIsXG4gICAgICAgIDgwLFxuICAgICAgICAxMjksXG4gICAgICAgIDEyNixcbiAgICAgICAgNDksXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTk5LFxuICAgICAgICAxNjksXG4gICAgICAgIDUwLFxuICAgICAgICAxNzEsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTE0LFxuICAgICAgICAyNDksXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTY0LFxuICAgICAgICA5MixcbiAgICAgICAgMTg4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjU0LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTgyLFxuICAgICAgICAxODUsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjIsXG4gICAgICAgIDQyLFxuICAgICAgICAyNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICA0NSxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICA0LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA0MixcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDEwMlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICA0NFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTkxLFxuICAgICAgICA3MixcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMjYsXG4gICAgICAgIDIyMyxcbiAgICAgICAgNDIsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTAyLFxuICAgICAgICA4LFxuICAgICAgICA0NSxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMDYsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjUzLFxuICAgICAgICAxNTEsXG4gICAgICAgIDQzLFxuICAgICAgICA1LFxuICAgICAgICAxNzgsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTAxLFxuICAgICAgICA5NSxcbiAgICAgICAgMjExLFxuICAgICAgICA4NyxcbiAgICAgICAgMTYwLFxuICAgICAgICAxNjQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjQ1LFxuICAgICAgICAyMjAsXG4gICAgICAgIDIyLFxuICAgICAgICAyNTIsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTIyLFxuICAgICAgICAyNixcbiAgICAgICAgMjA5LFxuICAgICAgICAxMjgsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTQxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTM2LFxuICAgICAgICAzOCxcbiAgICAgICAgNTEsXG4gICAgICAgIDMyLFxuICAgICAgICA3OSxcbiAgICAgICAgODQsXG4gICAgICAgIDcxLFxuICAgICAgICA1NSxcbiAgICAgICAgNzYsXG4gICAgICAgIDQwLFxuICAgICAgICAyMTYsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMjMsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjM0LFxuICAgICAgICAxODAsXG4gICAgICAgIDE5NixcbiAgICAgICAgNTgsXG4gICAgICAgIDQ0LFxuICAgICAgICA5OSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxMyxcbiAgICAgICAgMTQwLFxuICAgICAgICAxNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogOTMsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiVTVMazAwcVcwWE9mL3VBdGtvZzltR3AxQ2NmWkFBRXpqUFFZenRMd1RTOD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiYlpXV2YtRWdRTG0zOU1FS0FMU0E2d1wiLFxuICBcInBob25lSWRcIjogXCJiZTFhNjgyOC0zNDY2LTQ0OTctYjRmMi05NTM2OTg5OGM4ZDhcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTQ5LFxuICAgICAgMTI2LFxuICAgICAgMjAsXG4gICAgICAxMyxcbiAgICAgIDE2NixcbiAgICAgIDYyLFxuICAgICAgMjA2LFxuICAgICAgMTQ2LFxuICAgICAgMTc4LFxuICAgICAgNzUsXG4gICAgICAxOTksXG4gICAgICAyMDksXG4gICAgICA1MixcbiAgICAgIDE2OCxcbiAgICAgIDE5MixcbiAgICAgIDIzMCxcbiAgICAgIDIyLFxuICAgICAgMSxcbiAgICAgIDE3MyxcbiAgICAgIDc0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDc5LFxuICAgICAgMjI5LFxuICAgICAgMjMwLFxuICAgICAgMjAxLFxuICAgICAgMTM0LFxuICAgICAgMTc4LFxuICAgICAgODgsXG4gICAgICAyMTEsXG4gICAgICAxOTEsXG4gICAgICA0OCxcbiAgICAgIDIxNixcbiAgICAgIDExOCxcbiAgICAgIDIxMyxcbiAgICAgIDEzNyxcbiAgICAgIDQyLFxuICAgICAgMjIyLFxuICAgICAgMjQzLFxuICAgICAgMTA1LFxuICAgICAgMjM3LFxuICAgICAgMjA0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkIyN0FYWVBRXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ3MDM1ODU1MjgzOjQ5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiT2xhXCIsXG4gICAgXCJsaWRcIjogXCIzODI1MTI2NDAxMjUxMDo0OUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNLcXF6WnNIRU83U3RMZ0dHQU1nQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcImcycWl0N3MydkVSdVdRVXpTWFlzcnlpZnJNekFZZ0RzWWpvdWpQZWRtVWM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiN1VNd2hZc3FIV2k3cHdOYlJaV01xZGc0NWRRSG9LVTd2RnUyUDZ3ell2MXZ6ejBqNWN1NkQ4Q0ZEcmFyNnVpbzNHanBSZE80dmEvNFhGK3g4NXdzQWc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiVkNlUmN6bC9Sck1tWkpIU2pLY1NGOWxmQjdBVXVVclRrdVYzQWc0N3I1bzFuWkFqZi95d2oxSFVnRXpXYjZxR1ppdU9maDllNWZUMlNZbTQxSmhKQnc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0NzAzNTg1NTI4Mzo0OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICA0NCxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICA3MVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI4OTE1ODI3LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBQTdBXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBN0EuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJka1VkUlIyNVgxc2NhOG5rUzJxSXhLbFF3SEYyMWgyZUFmQ2dEWWRuZEd3PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE5MzY5MzgyODIsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyODc2NjUxNjgyN1wifSIKfQ==" //PUT SESSION-ID HERE


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ 𝕆𝕝𝕒😈🦍 MD 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "𝕆𝕝𝕒😈🦍 MD",
  ownername:process.env.OWNER_NAME|| "",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 
